on:
  push:
    branches:
      - main

jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check Node.js version
        run: node --version

      - name: Check npm version
        run: npm --version

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Start server
        run: npm start

      - name: Wait for server to start
        run: |
          n=0
          until [ $n -ge 5 ]
          do
            curl -I http://localhost:3000 && break
            n=$((n+1))
            sleep 10
          done
          if [ $n -eq 5 ]; then exit 1; fi
